// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smbmfawnxrpfmbjwpmna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtYm1mYXdueHJwZm1iandwbW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTYwODUsImV4cCI6MjA2Njg3MjA4NX0.G2t3AJJfiQ8rV3E_TGl3tDt3Ye8rZDBY2eKmUKfWsIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});